# Generated by Django 4.2.23 on 2026-02-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to='service/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(max_length=200, null=True, upload_to='product/'),
        ),
    ]
